services:
  postgres_db:
    image: postgres:12
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password 
  mongo_db:
    image: mongo:6
    ports:
      - "27017:27017"